### PR TITLE
13.0 mig l10n nl bank

### PR DESCRIPTION
**Pull request by lfreeke**

### CODE REVIEW

**Review by astirpe — APPROVED** [review]
Tested in Runbot: OK. Code review: OK.

**Review by StephanRozendaal — APPROVED** [review]
LGTM!

**Comment by hbrunn** [comment]
@lfreeke please fix the linting the oca bot complains about

**Comment by lfreeke** [comment]
@hbrunn branch should be mergable

**Review by hbrunn — APPROVED** [review]
I'll merge, if you want to add yourself as contributor you can do so in another PR

**Comment by hbrunn** [comment]
/ocabot merge
(or be fast enough before ocabot kicks in)

**Pull request merged**
