### PR TITLE
[ADD] l10n_nl_gdpr_processor_agreement

### PR DESCRIPTION
**Pull request by hbrunn**
this adds a report to print the processor agreement mandated by the GDPR for your customers. The result looks like this: [GDPR processor agreement (9).pdf](https://github.com/OCA/l10n-netherlands/files/2479836/GDPR.processor.agreement.9.pdf)

ping @pedrobaeza @jbeficent how do you do that? And would it make sense to move (parts of) this module to OCA/data-protection? The wording of course needs to change per legislation, but we might agree on how to identify the DPO and the like.

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@hbrunn 
I get:
`Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/_odoo/community/report_py3o/controllers/main.py", line 84, in report_download
    reportname, docids=docids, converter='py3o')
  File "/opt/odoo/_odoo/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/_odoo/community/report_py3o/controllers/main.py", line 52, in report_routes
    res, filetype = py3o_report.create_report(docids, data)
  File "/opt/odoo/_odoo/community/report_py3o/models/py3o_report.py", line 377, in create_report
    model_instance, data, save_in_attachment))
  File "/opt/odoo/_odoo/community/report_py3o/models/py3o_report.py", line 318, in _get_or_create_single_report
    model_instance, data, save_in_attachment)
  File "/opt/odoo/_odoo/community/report_py3o/models/py3o_report.py", line 260, in _create_single_report
    result_path, model_instance, data
  File "/opt/odoo/_odoo/community/report_py3o/models/py3o_report.py", line 279, in _convert_single_report
    command, cwd=os.path.dirname(result_path),
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

Don't know if this has to do with my environment. If so, consider not sent.

**Comment by hbrunn** [comment]
py3o (that's the reporting engine we use here) expects libreoffice to be available on the server. do you have that? thanks so much for testing anyways.

**Comment by CasVissers-360ERP** [comment]
@hbrunn Thanks working now. Will continue testing.

**Comment by CasVissers-360ERP** [comment]
First feedback:

1. It would be nice to be able to change the .odt file in the frontend.
2. _be sure to fill in this employee's title as it will be part of the agreement_ Function also will need to be set. 
3. Maybe nice to make the function field conditional.
4. I don't know if I like the solution to use the label field for registering the Data protection officer. Main reason being that it's not available in the form view of a contact when opening from within the company you want to print the agreement for.
5. I would be nice if we store the file as an attachment or even better in a new page "privacy"  or something similar. On that page we could also register the start and signed date. Maybe something is already available for this in OCA privacy. Haven't tested this yet.

**Comment by pedrobaeza** [comment]
@hbrunn by our part (Tecnativa), when GDPR arrived, we contacted specialized lawyers for adapting the company to the law, and we end up modifying our customer contracts to include the proper clauses about this, and the summary is:

- It depends on several variables. We have instances hosted by us, others hosted by the customer, others with special access to Postgres for external BI systems, etc, and each of them requires different clauses.
- It's integrated in the full contract, instead of a separate document.

So I think this shouldn't land OCA/data-privacy nor this PR, as putting this is to invade the lawyer ground and maybe incur in something missing.

**Review by NL66278 — APPROVED** [review]
LGTM. Maybe in instructions have some words on how users can edit the agreement.

**Comment by hbrunn** [comment]
closing this as I won't pursue it any further

**Pull request closed without merging**
