### PR TITLE
[13.0][MIG] l10n_nl_postcode

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by StephanRozendaal — CHANGES_REQUESTED** [review]
Please check the references in URLs in the README and index.html files related to the Odoo version, most still point to 12.0.

**Comment by astirpe** [comment]
@StephanRozendaal the README and the index.html file are automatically updated by the bot after the merge. I just updated the README manually. The bot will update the index.html file.

**Review by StephanRozendaal — APPROVED** [review]
LGTM!

**Review by hbrunn — APPROVED** [review]

**Pull request merged**
