### PR TITLE
[14.0][MIG] l10n_nl_bank

### PR DESCRIPTION
**Pull request by bosd**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM, thnx!

**Comment by StefanRijnhart** [comment]
Ideally, the update from https://github.com/OCA/l10n-netherlands/pull/299 should be a separate commit, cherry picked from your own PR branch (and I agree with renaming the migration scripts for 14.0.1.0.0 because not everybody will have updated the module in 13 before migrating to 14). Would that be alright for you?

**Comment by bosd** [comment]
> Ideally, the update from #299 should be a separate commit

True, It was my intention to do that. Clearly I had not followed the right workflow. Instead of rebasing should've used cherrypicking. Thanks for the hint.

Have been busy lately, will correct this. (But if it takes to long, feel free to merge this one)

> )not everybody will have updated the module in 13 before migrating to 14 Would that be alright for you?

Exactly my line of thinking

**Comment by bosd** [comment]
@StefanRijnhart Done fixing the commit history. Ready for merge now! :tada:

**Review by StefanRijnhart — APPROVED** [review]
Perfect, thanks!

**Review by astirpe — APPROVED** [review]

**Pull request merged**
