### PR TITLE
WIP: [8.0] [MIG] Backport l10n_nl_base_ubl

### PR DESCRIPTION
**Pull request by thomaspaulb**
From https://github.com/OCA/l10n-netherlands/pull/270

### CODE REVIEW

**Comment by NL66278** [comment]
@thomaspaulb I think if you tend to the following errors making travis red, we can merge this:
```
======== Testing test_flake8 ========

l10n_nl_account_invoice_ubl/models/account_invoice_ubl.py:5:1: F401 'openerp._' imported but unused

l10n_nl_account_invoice_ubl/models/account_invoice_ubl.py:7:1: F401 'openerp.tools.float_is_zero' imported but unused

l10n_nl_account_invoice_ubl/models/account_invoice_ubl.py:7:1: F401 'openerp.tools.float_round' imported but unused

l10n_nl_account_invoice_ubl/models/account_invoice_ubl.py:8:1: F401 'openerp.exceptions.Warning as UserError' imported but unused

l10n_nl_account_invoice_ubl/models/account_invoice_ubl.py:81:1: W391 blank line at end of file

l10n_nl_base_ubl/models/base_ubl.py:84:5: E303 too many blank lines (2)
```

**Comment by thomaspaulb** [comment]
@NL66278 Let's see!

**Comment by NL66278** [comment]
@thomaspaulb And now there is apparently a problem with finding the wkhtmltopdf binary when running tests.

**Comment by NL66278** [comment]
It keeps improving....

Now we have this:
```
File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/invoice2data/extract/invoice_template.py", line 69

def prepare_input(self, extracted_str: str) -> str:

^

SyntaxError: invalid syntax 
```
I think the type hint is python3 syntax.

**Comment by thomaspaulb** [comment]
Yea, I've debugged a bit and it seems to be because this depends on edi, and edi depends on invoice2data but apparently it installs some Python 3 version of invoice2data

I'm inclined to give up though, it's 8.0 and whoever's going to use this can just use my branch.

**Pull request merged**
