### PR TITLE
[ADD] Porting l10n_nl_bsn to V9

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by hbrunn** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Comment by RoelAdriaans** [comment]
Does this port have the same issue as #41? 
If so, maybe wait before merging until that error is fixed.

**Comment by astirpe** [comment]
Yes, the same issue #41 occurs on this port.
It's a very minor issue. It would probably never occur to an end user because, to reproduce it, you have to:
1. write a correct BSN and save
2. write a wrong BSN without saving
3. write the same BSN as point 1.

Is it a blocking issue for you?

**Comment by StefanRijnhart** [comment]
:+1:

**Pull request merged**
