### PR TITLE
[ADD] backport l10n_nl_tax_declaration_reporting from #63

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by hbrunn** [comment]
@astirpe I think #63 needs 927d6b0 too

**Comment by astirpe** [comment]
@hbrunn yes for sure! Feel free to open a PR to #63 if you want, I will merge it quickly. Otherwise I will include your fixes tomorrow. Thank you!

**Comment by hbrunn** [comment]
this needs tests

**Comment by StefanRijnhart** [comment]
As for the 10.0 version, I believe this module should be refactored to reformat the results of https://github.com/OCA/account-financial-reporting/tree/10.0/account_tax_balance instead of trying to reinvent the wheel of tax reporting.

**Comment by hbrunn** [comment]
absolutely! I was not aware of this module, thanks. Put to work in progress meanwhile

**Comment by StefanRijnhart** [comment]
And that module is not without its problems either https://github.com/OCA/account-financial-reporting/pull/284

**Comment by hbrunn** [comment]
I think we'll be better off with #74

**Pull request closed without merging**
