### PR TITLE
[MOD] add makepot="1" to travis.yml to tricker creation of pot files

### PR DESCRIPTION
**Pull request by lfreeke**

### CODE REVIEW

**Comment by lfreeke** [comment]
@hbrunn ping

**Review by astirpe — APPROVED** [review]

**Comment by hbrunn** [comment]
hmm, I don't see any messages relating to the pot generation, it seems we're missing something.

**Comment by hbrunn** [comment]
ah, we'll have to actually merge this for stuff to happen. I'll do so, then we should see something during the build of the main branch. I'll take the liberty to change your commit message

**Comment by hbrunn** [comment]
this looks good now: https://travis-ci.org/OCA/l10n-netherlands/jobs/430025788#L2020

Can you check in a while if the update shows up on weblate, and if so, cherry pick this commit to 8, 9, 11?

**Comment by lfreeke** [comment]
I will cherry pick this. The translation show up in weblate.

**Pull request merged**
