### PR TITLE
[MIG] [12.0] l10n_nl_partner_name

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM, functional review.

**Comment by CasVissers-360ERP** [comment]
@hbrunn 
One small point of feedback, see video:
https://drive.google.com/file/d/1w9lYJni3gYfwGAV_Id_AYOUsoBGlFm3O/view

Might be an issue of partner_firstname?

**Comment by hbrunn** [comment]
I don't really understand what I see. When you reset the email address, the contact form changes? This looks to me like there's some form that needs the correct conditional invisibility

**Comment by hbrunn** [comment]
we'll need a fix for `l10n_nl_tax_statement` anyways before we can start merging in 12 again

**Comment by astirpe** [comment]
I don't have time to investigate why tests of `l10n_nl_tax_statement` suddenly fail.
For me the failing tests can be temporarily commented out, as done in https://github.com/OCA/l10n-netherlands/pull/250/commits/a40dc5964cbca5e45e1bb7de6f2b344aac53eb5b.
I'll try to fix them when I have enough time.

**Comment by CasVissers-360ERP** [comment]
> I don't really understand what I see. When you reset the email address, the contact form changes? This looks to me like there's some form that needs the correct conditional invisibility

When a partner has no e-mail set, and you want to send out a sale order or invoice. Odoo prompts for an e-mail. In the view first_name and last_name is shown although the contact of the object is a company.

**Comment by hbrunn** [comment]
@CasVissers thanks, this should be fixed now

@astirpe anybody else can dig into this too, so I don't see you as the one who is solely responsible to fix this. 'Fixing' tests by deactivating them is something I only want to do in exceptional cases.

Probably the issue is the new year, so we might have to make some of the dates involved in the tests relative to the current date.

**Review by CasVissers-360ERP — APPROVED** [review]
Thnx, fixes the issue.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
