### PR TITLE
[ADD] partner name dutch

### PR DESCRIPTION
**Pull request by hbrunn**
This depends on partner_firstname from https://github.com/OCA/partner-contact

### CODE REVIEW

**Comment by NL66278** [comment]
:+1:  As this is a simple transfer from one project to another, no need to test

**Comment by diellenne** [comment]
Very nice, thank you for contributing! I'm gonna add your module in the roadmap and in the Dutch community modules list. Just a couple of things:
- for all the community modules I'd really like to keep the prefix l10n_nl_ in the module name
- please don't use your company logo as a module icon: I totally understand but I think that the icon of the module should be something related with with the module purpose; in alternative we can design our own icon to use for all the Dutch community modules.

Cheers...

**Comment by hbrunn** [comment]
Thanks, the logo is indeed wrong, the OCA has an agreement that there shouldn't be company logos in OCA modules. I'll fix that soon. Is there already some Dutch localization logo floating around?

As for the name: I consider a prefix that is the same for all modules in a repo redundant, but that's open to discussion of course.

**Comment by diellenne** [comment]
:+1: 

For the module names I wanted to add the prefix to:
- clearly identify the modules of our community even when they are mixed with other modules
- be aligned with the other localization projects

Actually we don't have a logo...I'm opening an issue for it ;-)

**Comment by hbrunn** [comment]
okay, here we go

**Comment by diellenne** [comment]
Thank you.
This afternoon or tomorrow in the morning I'm gonna make a quick test of the module; if everything will be ok I will merge it!

Cheers.

**Comment by diellenne** [comment]
For some contingency I have to postpone (just a bit) the revision of the module but I will do it really ASAP.
In the next days I'm planning to expand the project team to have more persons able to review the modules in order to release better products and speed up the development process.

**Comment by NL66278** [comment]
:+1:  Once more, but now after testing.

**Comment by StefanRijnhart** [comment]
Can you add the pot file?

**Comment by hbrunn** [comment]
done

**Comment by StefanRijnhart** [comment]
Thanks! Merging this as it seems you have addressed Diego's points from more than 6 weeks ago.

**Pull request merged**
