### PR TITLE
[ADD] l10n_nl_normalize_zip

### PR DESCRIPTION
**Pull request by hbrunn**
Normalize Dutch zip codes
=========================

This module was written to have zipcodes formatted in the standard Dutch way, which is 0000 XX.

Usage
=====

To use this module, you need to:

#. fill in a zip number on a partner
#. be happy that whatever you fill in there, if it looks remotely like a Dutch zip code, it will be forced to the format above.

### CODE REVIEW

**Comment by hbrunn** [comment]
@pedrobaeza can you add server-tools to runbot?

**Comment by astirpe** [comment]
@hbrunn with this module you format the zip for every partner regardless if it's country is Netherlands or not. Is it correct? In this case is it possible to format the zip depending on the Country if it's already set?

**Comment by pedrobaeza** [comment]
server-tools added in runbot and rebuild launched

**Comment by hbrunn** [comment]
@pedrobaeza thanks!
@astirpe I consider it correctish ;-) Note that the code is quite cautious about not touching strings that don't look like Dutch zip codes. A check for the first 4 being digits and the last two being characters wouldn't hurt I guess though, added this right now.

Judging from https://en.wikipedia.org/wiki/List_of_postal_codes, the Dutch format is unique, so it shouldn't clash with some other country and we avoid reading the partners for every write on the zip code.

**Comment by NL66278** [comment]
:+1:  LGTM

**Comment by andreschenkels** [comment]
:+1:

**Comment by astirpe** [comment]
@hbrunn when installing the module, the zip value of existing partners is not automatically updated; was it intentional to not provide a post_init_hook for normalizing the zip for all the existing partners?

Code review is :+1:  for me

**Comment by hbrunn** [comment]
intentional as in not relevant for my current problem. It's certainly a good thing to have for people who want to install this in an existing database, should be very straightforward to add

**Comment by hbrunn** [comment]
can we merge this?

**Review by pankk — APPROVED** [review]
Reviewed code, looks great!

**Review by tarteo — APPROVED** [review]
👍

**Pull request merged**
