### PR TITLE
[11.0][MIG] l10n_nl_xaf_auditfile_export

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]
CI provided

Out of interest, not because I want to force you to do it: Did you check if the xml namespace hack is necessary still?

**Comment by astirpe** [comment]
@hbrunn I didn't know there was a hack, I will check it.
Can I ask the "Work in progress" label for this?

**Comment by astirpe** [comment]
Oh, and do you allow me to shorten the headers with the Therp copyrights?

**Comment by hbrunn** [comment]
sure, we care about the copyright itself, not how it's presented. Great you're curious about the namespaces. The story here is that i didn't manage to add the namespace already to the qweb template, this would be a lot simpler and than most of the dance in https://github.com/OCA/l10n-netherlands/pull/124/files#diff-505075f9c857078662857d71a223763cR102 wouldn't be necessary any more. But back then (and because of the way lxml handles namespaces) this won't fly. But given the qweb engine by now is xml describing autogenerated python code, this might just work...

**Comment by astirpe** [comment]
Still some rounding issues to be fixed

**Comment by astirpe** [comment]
I'm realizing right now that the fix in this commit: https://github.com/OCA/l10n-netherlands/pull/124/commits/5caef414f7d0b42595fb88d4fa91ddbd3c566240 could be rewritten in a simpler way, working on it...

**Comment by astirpe** [comment]
@yung-wang can you help me with the intensive tests? :)

**Comment by astirpe** [comment]
Commit https://github.com/OCA/l10n-netherlands/pull/124/commits/dd91b3833b5605aa49aaba2327647a441c166226 is an alternative approach to fix issue https://github.com/OCA/l10n-netherlands/pull/75.

My proposal is to make use of `write_uid.id` instead of `write_uid.login`.
This way we don't need to cut the `write_uid.login` to 35 characters.

**Review by yung-wang — COMMENTED** [review]
I tested it with some invoices and it seems to work fine. I cannot find an error in the generated XAF file. But we need an extra check for this.

**Comment by hbrunn** [comment]
absolutely agreed with the uid, weird we didn't use this from the start

**Comment by astirpe** [comment]
@hbrunn I will not be able to check the namespace matter during the next two weeks, but I will check it later on. In the meanwhile may I ask you to set this PR to "Needs review"?

**Comment by astirpe** [comment]
@hbrunn I tried with a partial revert of commit https://github.com/OCA/l10n-netherlands/pull/124/commits/4492ddc8d9a696e609d7ef4d002e62872c993c95, to avoid the injection of the namespace, but at the end it didn't work. Maybe I will play with it again in the future when I will have enough time, for the moment I would keep the things as they are.

**Comment by hbrunn** [comment]
sorry, I forgot to post the result of my own experiments with this (just stick an fodt into a qweb template. Should work but doesn't because no namespace support), and ended up patching core massively. Just to find out master already has this already: https://github.com/odoo/odoo/pull/14869 (didn't test if it works though)

**Review by melroy89 — APPROVED** [review]
YES I want this!

**Comment by melroy89** [comment]
@pedrobaeza Please merge.

**Comment by pedrobaeza** [comment]
Same answer as https://github.com/OCA/l10n-netherlands/pull/122#issuecomment-355966970

**Comment by melroy89** [comment]
Could you merge it @hbrunn ?

**Comment by melroy89** [comment]
@astirpe OOpsy daisy.

I'm getting:

```
Fout:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_1480_89
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py", line 213, in get_move_line_count
    (self.date_start, self.date_end, self.company_id.id, ))
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near "2018"
LINE 1: ...t count(*) from account_move_line where date >= ''2018-01-01...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fbccf637828>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 367, in get_template
    document = options.get('load', self.load)(template, options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1053, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-28>", line 2, in _read_template
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 82, in lookup
    key = key0 + self.key(*args, **kwargs)
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 951, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2565, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_users.py", line 872, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_users.py", line 302, in read
    result = super(Users, self).read(fields=fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2509, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2628, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py", line 80, in button_generate
    'self': self,
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1158, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1167, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    element, document = self.get_template(template, options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 371, in get_template
    raise QWebException("load could not load template", name=template)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: None
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_1480_89
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py", line 213, in get_move_line_count
    (self.date_start, self.date_end, self.company_id.id, ))
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near "2018"
LINE 1: ...t count(*) from account_move_line where date >= ''2018-01-01...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fbccf637828>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 367, in get_template
    document = options.get('load', self.load)(template, options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1053, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-28>", line 2, in _read_template
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 82, in lookup
    key = key0 + self.key(*args, **kwargs)
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 951, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1052, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2565, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_users.py", line 872, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/res/res_users.py", line 302, in read
    result = super(Users, self).read(fields=fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2509, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2628, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block


load could not load template
Template: 1480
```

**Comment by astirpe** [comment]
@danger89 I'm very sorry, my bad. Please check https://github.com/OCA/l10n-netherlands/pull/140

**Pull request merged**
