### PR TITLE
[14.0][MIG] l10n_nl_tax_statement

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM, code review. No weird changes.

**Comment by astirpe** [comment]
Strange, I rebased and pushed and this PR was automatically closed

**Comment by astirpe** [comment]
Was a wrong rebase. Will open a new PR

**Comment by astirpe** [comment]
Opened https://github.com/OCA/l10n-netherlands/pull/298

**Pull request closed without merging**
