### PR TITLE
[11.0][IMP] Move repository to github actions

### PR DESCRIPTION
**Pull request by NL66278**

### CODE REVIEW

**Comment by NL66278** [comment]
@astirpe Need a combination of moving to pre-commit and github actions instead of travis, togheter with improvements to kvk and postcode modules to get everything merged and finally get all the other 11.0 PR's finalized.

**Review by astirpe — APPROVED** [review]
Thank you!

**Comment by NL66278** [comment]
@astirpe Apparently for some reason ocabot does not work for this PR. Shall I just merge it using the normal github action?

**Review by thomaspaulb — APPROVED** [review]
I've removed the merge commits.

**Comment by thomaspaulb** [comment]
Seems the `l10n_nl_location_nuts` item is now failing on [this url](https://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=ACT_OTH_CLS_DLD&StrNom=NUTS_2013&StrFormat=XML&StrLanguageCode=EN&StrLayoutCode=HIERARCHIC) not working, being defined [here](https://github.com/OCA/partner-contact/blob/11.0/base_location_nuts/wizard/nuts_import.py#L18). Apparently this has gone elsewhere, and they're having the same problem in https://github.com/OCA/partner-contact/pull/1398 as well.

Where did it go?

**Pull request merged**
