### PR TITLE
[11.0][FIX] l10n_nl_tax_statement: report

### PR DESCRIPTION
**Pull request by astirpe**
Fix for https://github.com/OCA/l10n-netherlands/issues/142

### CODE REVIEW

**Comment by astirpe** [comment]
@elperrofarelo @danger89 may I ask you to try with this fix?

**Comment by melroy89** [comment]
OK I will try it, be noted that runbot is still failing.

**Review by yung-wang — APPROVED** [review]
I tried the report print on runbot and it works. It is fixed.

**Comment by astirpe** [comment]
@danger89 Runbot is red, but it's just because there is a warning in the logs. It happens also in other pull requests. That warning is not blocking.
You can use Runbot for your tests, it works fine.

**Comment by astirpe** [comment]
Rebased and squashed, let's see what Runbot says this time..

**Comment by melroy89** [comment]
Tested & validated. Seems to work again, thanks.

[BTW-aangite.zip](https://github.com/OCA/l10n-netherlands/files/1646603/BTW-aangite.zip)

Although I see a typo here in the name of the generated PDF file name 😆 ..
https://github.com/OCA/l10n-netherlands/blob/fac167ee04c5e8b3a2198f0f09d8ec8fe5fa681b/l10n_nl_tax_statement/i18n/nl.po#L373

**Comment by astirpe** [comment]
@danger89 the typo "BTW-aangite" is in the nl.po file. I guess it can be fixed by Transifex.

**Comment by melroy89** [comment]
@astirpe Yea I know. Fixed it already 👍 
image

**Comment by astirpe** [comment]
@danger89 you are super fast! (like Odoo 11)

**Comment by melroy89** [comment]
@astirpe Time is money ^^ haha

**Review by melroy89 — APPROVED** [review]

**Comment by melroy89** [comment]
LGTM

**Comment by elperrofarelo** [comment]
Thanks. It's working now

**Pull request merged**
