### PR TITLE
[11.0][MIG] l10n_nl_postcodeapi

### PR DESCRIPTION
**Pull request by astirpe**
Depends on:

- [x] https://github.com/steffex/pyPostcode/pull/16

TODO:
- [x]  add tests
- [x]  remove temporary workaround (awaiting update of PyPI with https://github.com/steffex/pyPostcode/pull/16)

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test successful.

**Comment by CasVissers-360ERP** [comment]
A normal user has no permission to read ir.config_parameter resulting in an access right warning. Can we fix this?

**Comment by astirpe** [comment]
@CasVissers can you check now?

**Review by CasVissers-360ERP — APPROVED** [review]
Thanks.

**Comment by astirpe** [comment]
Coverage will increase after the removal of the temporary workaround.

**Comment by CasVissers-360ERP** [comment]
When you reach the max amount of credits per day, or the API key is incorrect. Changes are not saved to the partner form.

**Comment by astirpe** [comment]
@CasVissers I see, thank you! I guess it also happens with previous versions.

**Comment by astirpe** [comment]
@CasVissers could you try now?

**Review by CasVissers-360ERP — APPROVED** [review]

**Comment by astirpe** [comment]
Any chance to update the PyPI with the latest pyPostcode? Otherwise I would propose a solution to make this module not depending on that library.

**Comment by StefanRijnhart** [comment]
@astirpe I'm sorry, I forgot that I have those privileges on the PyPostcode project. I released 0.5 https://pypi.org/project/pyPostcode/ /cc @steffex

**Comment by astirpe** [comment]
Thanks!

**Review by hbrunn — APPROVED** [review]

**Pull request merged**
