### PR TITLE
[11.0][FIX] l10n_nl_bsn: searching on BSN without dots

### PR DESCRIPTION
**Pull request by astirpe**
Backport of https://github.com/OCA/l10n-netherlands/pull/232 to V11

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by NL66278** [comment]
Aborted because of (unrelated) error: connection to kvk site not available. Will retry later...

**Comment by astirpe** [comment]
The connection problem of l10n_nl_kvk is caused by the recent changes (october 2020) made on the KVK API regarding the security policy.

As written in the KVK API developers documentation:

> The KVK uses private certificates for all machine to machine connections, this includes the KVK API. This means that your software will not trust our certificate by default.In order to communicate with the KVK API’s you will have to manually configure your software to trust our certificate. How to configure this depends on the platform used by your software.

I'm going to fix this issue.

**Comment by astirpe** [comment]
Connection issue seems fixed

**Pull request merged**
