### PR TITLE
[8.0][MIG] Backport of l10n_nl_oin

### PR DESCRIPTION
**Pull request by thomaspaulb**
It's used in, although not required for,

https://github.com/OCA/l10n-netherlands/pull/290

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@NL66278 I want to make the runbot green here. It gets to [this point](https://github.com/OCA/maintainer-quality-tools/blob/master/travis/test_server.py#L466), but after that I _think_ the MAKEPOT times out and gets killed. I've tried different MAKEPOT configurations, but I can't seem to fix it. Do you know what's going on, or who I can ask? I thought I'd try you first, since I believe you are a PSC here, although I'm not sure.

**Comment by thomaspaulb** [comment]
The offending log:

https://runbot.odoo-community.org/runbot/static/build/3452759-292-737b33/logs/job_20_test_all.txt

**Comment by thomaspaulb** [comment]
I think it has nothing to do with my code though, so I'm continuing the green-quest separately in https://github.com/OCA/l10n-netherlands/pull/294.

**Comment by NL66278** [comment]
@thomaspaulb But you have to fix this one:
2020-11-26 13:24:40,968 160 WARNING openerp_test openerp.addons.base.module.module: module l10n_nl_oin: description is empty !

**Comment by thomaspaulb** [comment]
@NL66278 About that: I have left README.rst empty because I assumed it would be filled by the `oca-gen-addon-readme` script automatically. Or do I need to do that proactively in my local?

**Comment by NL66278** [comment]
@thomaspaulb Close and re-open this after we get the general PR for 8.0 green. That will run buildout and travis again.

**Comment by NL66278** [comment]
I think normally it should do this. Maybe not yet for 8.0. So bet to do it manually...

**Comment by gjotten** [comment]
LGTM functionally

**Review by gjotten — APPROVED** [review]

**Review by astirpe — APPROVED** [review]
Code review only (not tested).

**Pull request merged**
