### PR TITLE
[11.0] [MIG] letsencrypt_transip_nl

### PR DESCRIPTION
**Pull request by NL66278**
Without the postcode api changes.

### CODE REVIEW

**Comment by NL66278** [comment]
runboat failes with:
```
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/c
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-d71agB/python3.5-3.5.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/opt/odoo-venv/include -I/usr/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.5/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
       15 | #include <ffi.h>
          |          ^~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/odoo-venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oorbucew/cffi_990111df262e4e3cba1f17ce0f008922/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oorbucew/cffi_990111df262e4e3cba1f17ce0f008922/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x7ksmbq1/install-record.txt --single-version-externally-managed --compile --install-headers /opt/odoo-venv/include/site/python3.5/cffi Check the logs for full command output.
```

**Review by tarteo — APPROVED** [review]
LGTM ran tests locally.
```
2022-05-11 13:44:44,979 20092 INFO 11_l10n_nl_letsencrypt_transip_nl odoo.addons.l10n_nl_letsencrypt_transip_nl.tests.test_letsencrypt_transip_nl: Ran 4 tests in 0.163s
2022-05-11 13:44:44,979 20092 INFO 11_l10n_nl_letsencrypt_transip_nl odoo.addons.l10n_nl_letsencrypt_transip_nl.tests.test_letsencrypt_transip_nl: OK
```

**Comment by NL66278** [comment]
Possibly runboat error related to this: https://stackoverflow.com/questions/62658237/it-seems-that-the-version-of-the-libffi-library-seen-at-runtime-is-different-fro

**Comment by NL66278** [comment]
Another error on runboat, but now it actually is related to the module. Have to research this:
```
2022-05-13 08:37:05,781 104 WARNING b24672786-e482-4585-a4bf-fd9eb3046f31 py.warnings: /opt/odoo-venv/lib/python3.5/site-packages/transip/client.py:13: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.hazmat.backends import default_backend

2022-05-13 08:37:05,815 104 WARNING b24672786-e482-4585-a4bf-fd9eb3046f31 odoo.modules.loading: Transient module states were reset
2022-05-13 08:37:05,815 104 ERROR b24672786-e482-4585-a4bf-fd9eb3046f31 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 383, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/modules/loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "/opt/odoo/odoo/modules/registry.py", line 275, in setup_models
    model._setup_base()
  File "/opt/odoo/odoo/models.py", line 2428, in _setup_base
    self._add_field(name, field.new())
  File "/opt/odoo/odoo/models.py", line 290, in _add_field
    field.setup_base(self, name)
  File "/opt/odoo/odoo/fields.py", line 380, in setup_base
    self._setup_attrs(model, name)
  File "/opt/odoo/odoo/fields.py", line 1804, in _setup_attrs
    self.selection = list(OrderedDict(self.selection + selection_add).items())
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
2022-05-13 08:37:05,816 104 CRITICAL b24672786-e482-4585-a4bf-fd9eb3046f31 odoo.service.server: Failed to initialize database `b24672786-e482-4585-a4bf-fd9eb3046f31`.
Traceback (most recent call last):
  File "/opt/odoo/odoo/service/server.py", line 1054, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 383, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/modules/loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "/opt/odoo/odoo/modules/registry.py", line 275, in setup_models
    model._setup_base()
  File "/opt/odoo/odoo/models.py", line 2428, in _setup_base
    self._add_field(name, field.new())
  File "/opt/odoo/odoo/models.py", line 290, in _add_field
    field.setup_base(self, name)
  File "/opt/odoo/odoo/fields.py", line 380, in setup_base
    self._setup_attrs(model, name)
  File "/opt/odoo/odoo/fields.py", line 1804, in _setup_attrs
    self.selection = list(OrderedDict(self.selection + selection_add).items())
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

**Pull request closed without merging**
