### PR TITLE
[13.0][FIX] l10n_nl_bsn: search bsn with dots

### PR DESCRIPTION
**Pull request by astirpe**
Forward port of latest changes made on https://github.com/OCA/l10n-netherlands/pull/232

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
I see this is a followup of https://github.com/OCA/l10n-netherlands/pull/242

**Review by CasVissers-360ERP — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Apparently, the nuts import attempts a live connection to a remote server which does not respond consistently
```
2021-03-01 12:38:42,526 5997 INFO openerp_test odoo.addons.l10n_nl_location_nuts.tests.test_l10n_nl_location_nuts: Starting TestNlLocationNuts.test_post_init_hook ...

2021-03-01 12:38:42,543 5997 INFO openerp_test odoo.addons.base_location_nuts.wizard.nuts_import: Importing NUTS 2013 English...

2021-03-01 12:38:42,544 5997 INFO openerp_test odoo.addons.base_location_nuts.wizard.nuts_import: Starting to download http://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=ACT_OTH_CLS_DLD&StrNom=NUTS_2013&StrFormat=XML&StrLanguageCode=EN&StrLayoutCode=HIERARCHIC

2021-03-01 12:38:47,325 5997 INFO openerp_test odoo.addons.l10n_nl_location_nuts.tests.test_l10n_nl_location_nuts: ======================================================================

2021-03-01 12:38:47,325 5997 ERROR openerp_test odoo.addons.l10n_nl_location_nuts.tests.test_l10n_nl_location_nuts: ERROR: TestNlLocationNuts.test_post_init_hook

Traceback (most recent call last):

File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen

chunked=chunked)

File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request

six.raise_from(e, None)

File "<string>", line 2, in raise_from

File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request

httplib_response = conn.getresponse()

File "/opt/python/3.6.7/lib/python3.6/http/client.py", line 1331, in getresponse

response.begin()

File "/opt/python/3.6.7/lib/python3.6/http/client.py", line 297, in begin

version, status, reason = self._read_status()

File "/opt/python/3.6.7/lib/python3.6/http/client.py", line 258, in _read_status

line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

File "/opt/python/3.6.7/lib/python3.6/socket.py", line 586, in readinto

return self._sock.recv_into(b)

File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 302, in recv_into

raise SocketError(str(e))

OSError: (104, 'ECONNRESET')
```

It would be better to replace this live connection with a mock passing a recorded response.

**Comment by astirpe** [comment]
I opened https://github.com/OCA/l10n-netherlands/pull/309 for a solution with mocked tests

**Comment by NL66278** [comment]
It is now failing on another probably unrelated error:
```
ERROR: TestTaxInvoiceBasis.test_02_tax_standard

Traceback (most recent call last):

  File "/home/travis/build/OCA/l10n-netherlands/l10n_nl_tax_invoice_basis/tests/test_tax_invoice_basis.py", line 91, in test_02_tax_standard

    self.invoice.action_post()

  File "/home/travis/odoo-13.0/addons/account/models/account_move.py", line 2345, in action_post

    return self.post()

  File "/home/travis/odoo-13.0/addons/account/models/account_move.py", line 2241, in post

    raise UserError(_('The entry %s (id %s) is already posted.') % (move.name, move.id))

odoo.exceptions.UserError: ('The entry BILL/2017/0001 (id 18) is already posted.', '')
```

**Pull request merged**
