### PR TITLE
[13.0][MIG] l10n_nl_xaf_auditfile_export

### PR DESCRIPTION
**Pull request by astirpe**
Includes https://github.com/OCA/l10n-netherlands/pull/247
Includes https://github.com/OCA/l10n-netherlands/pull/250
Includes https://github.com/OCA/l10n-netherlands/pull/255

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thank you!

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM, functional review

**Comment by StefanRijnhart** [comment]
Can you check travis? 
```2020-03-19 11:05:51,666 5744 ERROR openerp_test odoo.addons.l10n_nl_xaf_auditfile_export.models.xaf_auditfile_export: Element '{http://www.auditfiles.nl/XAF/3.2}fiscalYear': [facet 'maxLength'] The value has a length of '42'; this exceeds the allowed maximum length of '9'. (<string>, line 0)```

**Comment by astirpe** [comment]
@StefanRijnhart All green!

**Comment by StefanRijnhart** [comment]
Perfect!
/ocabot merge

**Pull request merged**
