### PR TITLE
[MIG][10.0] l10n_nl_intrastat

### PR DESCRIPTION
**Pull request by astirpe**
Based on the job made in https://github.com/OCA/l10n-netherlands/pull/57

### CODE REVIEW

**Comment by jvOrsouw** [comment]
Yes, all validated revenue is now shown in this report.

Great addition for dutch localization

👍

**Review by StefanRijnhart — CHANGES_REQUESTED** [review]
Very useful, thank you! Needs a rebase.

**Comment by astirpe** [comment]
@StefanRijnhart rebased. Thank you!

**Review by StefanRijnhart — APPROVED** [review]
Code review and test.

Would be good if you could fix the misnomer in this module's title and description, replacing 'Intrastat' with Intracom Tax Report or something as Intrastat is something else.

**Comment by astirpe** [comment]
@StefanRijnhart done, would you take a second check?

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the update on the name and description!

**Comment by hbrunn** [comment]
I count @jvOrsouw's old style thumbs as an approval too, enough working days, so let's merge (@jvOrsouw please use github's review mechanism too, this makes it so much more convenient for maintainers)

**Pull request merged**
