### PR TITLE
[UPD] update translation for 10

### PR DESCRIPTION
**Pull request by lfreeke**

### CODE REVIEW

**Comment by leemannd** [comment]
@lfreeke Hello, thanks for the contribution, but since a few days ago the best way to update translation was using transifex. The as the community is moving to weblate, could you consider using https://translation.odoo-community.org/ ?

**Comment by lfreeke** [comment]
@leemannd  Hi, 
There were no translations strings available in Transifex. 
Maybe it is a bug in Transifex. Will have a look at it.

**Comment by leemannd** [comment]
Hello, as I heard at the code sprint there is an ongoing transition to https://translation.odoo-community.org/

**Comment by lfreeke** [comment]
@leemannd Top will do translation over there. But still no strings available for the partner_salutation module. Should I do something to make sure the strings are fetch by weblate?

**Comment by leemannd** [comment]
@lfreeke I can't tell. @moylop260 do you have any idea about it?

**Comment by moylop260** [comment]
@jesuszapata Could you help us to upload the terms translations for  https://translation.odoo-community.org/projects/github_com_OCA_l10n-netherlands_10_0/l10n_nl_partner_salutation ?

(Currently is empty)

**Comment by JesusZapata** [comment]
@moylop260 Now the project [l10n-netherlands](https://translation.odoo-community.org/projects/github_com_OCA_l10n-netherlands_10_0/l10n_nl_partner_salutation/) show the languages and the words to translated

@lfreeke Now you can login in [translation.odoo-community.org](https://translation.odoo-community.org/accounts/login/) using your github account

**Comment by lfreeke** [comment]
@JesusZapata @moylop260 @leemannd 
The translation are now on weblate. 

Thanks, I will close this pull request.

**Pull request closed without merging**
