### PR TITLE
[11.0][MIG] l10n_nl_country_states

### PR DESCRIPTION
**Pull request by astirpe**
This is the porting of `l10n_nl_country_states` to V11.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't interesting for you to switch to `base_location_geonames_import` module + maybe a little adaptation like the one in Spanish localization: https://github.com/OCA/l10n-spain/tree/11.0/l10n_es_toponyms ?

**Comment by astirpe** [comment]
@pedrobaeza the `base_location_geonames_import` seems to me not fitting very well for the Dutch localization.
The number of provinces is very small in the Netherlands. On the other side, we need to track the postcode ranges per province, which seems to me an information that is not present in the geonames.

**Comment by pedrobaeza** [comment]
OK, understood.

**Review by hbrunn — CHANGES_REQUESTED** [review]
I think your changes will yield unexpected results for partial writes, that was my reasoning for doing it in a somewhat convoluted way. When we write a zip code (and only that) on some partner in a non-Dutch country, and the zip code happens to be in our list, we'll write the state, right?

Further, can you share the code you used to combine intervals or was that some manual post processing?

**Comment by astirpe** [comment]
@hbrunn you're right! I will restore the previous behavior. Thanks!

**Comment by astirpe** [comment]
I restored the old behavior, adding tests to cover the case of writing the zip (and only the zip).
I updated the script with the one used for combining the intervals. The script assumes that the records of the .xls are sorted by postcode number.

**Comment by astirpe** [comment]
Commit https://github.com/OCA/l10n-netherlands/pull/189/commits/f35ac00c2a452e89e373516363f7fbdcd3dfa374 is meant to avoid conflicts with tests of `l10n_nl_postcodeapi`.
It's a ugly but quick fix. If you have better ideas just let me know :)

**Review by hbrunn — APPROVED** [review]
thanks. I think we can also just have the postcode module depend on this one, but the changed test is fine with me too.

**Review by tarteo — APPROVED** [review]

**Comment by astirpe** [comment]
Can this one be merged?

**Pull request merged**
