### PR TITLE
[14.0][MIG] l10n_nl_postcode

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Review by bosd — COMMENTED** [review]
LGTM, minor detail, this commit is missing: https://github.com/OCA/l10n-netherlands/commit/e7f4bd3e1ad9c817ea50b92edb7ab8f1d75b7dcc

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM @bosd translations will be automatically updated.

**Review by bosd — APPROVED** [review]

**Pull request merged**
