### PR TITLE
[12.0][FIX/IMP] l10n_nl_tax_statement: add past invoices in report

### LINKED ISSUE #219: [V11] l10n_nl_tax_statement: Update of past undeclared invoices - Update of BTW statement doesn't work
Hello,

i have just checked the V11 version of l10n_nl_tax_statement in order to adopt it for the german "clone" of this module: https://github.com/openbig/l10n-germany/tree/10.0/l10n_de_tax_statement.

I have created a customer invoice with the tax "Verkopen/omzet hoog" with a invoice date in between of the given date_range in the tax statement. If i click on update button the value in the line "1a Leveringen/diensten belast met hoog tarief"  was calculated correctly.

Now i created two further invoices with a invoice date before the "from_date" of the statement. If i go to the tab "Past undeclared invoices" i can see the two lines. Now i wanted to include those lines in the statement by clicking on the ">" arrow to add them + clicking on the "update" button as suggested by the description "Add/Remove the Undeclared Invoices listed below. Afterwards press the Update button in order to recompute the statement lines!".

bildschirmfoto 2019-02-08 um 10 20 50

Now i would normally expect that the line "1a Leveringen/diensten belast met hoog tarief" would have been updated but it doesn't.

bildschirmfoto 2019-02-08 um 10 22 05

Unfortunately it just shows the "regular" invoice in between of the given date range. I miss here the two further added invoices from the past months.

bildschirmfoto 2019-02-08 um 10 22 35

Nevertheless, thanks a lot for your great work on that module. The added feature "past undeclared invoices" is a great further improvement. I will now try to adopt the V11 changes for the german accounting plans.

Best regards
Thorsten

### PR DESCRIPTION
**Pull request by astirpe**
Fixes #219
Forward port of https://github.com/OCA/l10n-netherlands/pull/220

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@astirpe 
Add invoice button seems not showing:
image

**Comment by CasVissers-360ERP** [comment]
@astirpe Can we sort on from_date? Makes more sense in tree view.

**Comment by astirpe** [comment]
@CasVissers done! Could you check?

**Comment by CasVissers-360ERP** [comment]
@astirpe 
Possible improvements:
- Limit invoices to last 5 year based on fiscal year end date (legal requirement)
- When adding invoices automatically recalculate the tax statement (now a manual recalculate is necessary)
- The unreported from date is calculate as 1 quarter I would take 1 fiscal year based on fiscal year end date

What do you think?

_Of course this only takes care of new invoices, not removed invoices_

**Comment by astirpe** [comment]
Thank you @CasVissers , I updated the roadmap with the points you proposed.

**Comment by CasVissers-360ERP** [comment]
@astirpe 
I will approve if this point is fixed:
> When adding invoices automatically recalculate the tax statement (now a manual recalculate is necessary)

I think this should be improved.

**Comment by astirpe** [comment]
@CasVissers done, could you check?

**Review by CasVissers-360ERP — APPROVED** [review]
👍

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Thanks. Great module ;-)

**Pull request merged**
