### PR TITLE
[14.0][MIG] l10n_nl_oin

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
According to the [migration bible](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0) you should squash the two middle commits, otherwise LGTM

**Review by thomaspaulb — APPROVED** [review]

**Comment by astirpe** [comment]
I prefer to wait the time when the OCA bot will be capable to squash the administrative commits by himself. Otherwise I should start to chase him in every PR I open :)

**Comment by thomaspaulb** [comment]
@astirpe Fair enough :)

**Review by StefanRijnhart — APPROVED** [review]
I'm not even sure that administrative commits of various domains should be squashed together :-O. A matter of opinion I hope.

**Pull request merged**
