### PR TITLE
[13.0][MIG] l10n_nl_kvk

### PR DESCRIPTION
**Pull request by astirpe**
Depends on:

- [x] https://github.com/OCA/l10n-netherlands/pull/274

### CODE REVIEW

**Comment by bosd** [comment]
Functional review:
LGTM! one little remark.

In the screen
kvk preview -> open line 
What does the text “wizard = false” mean?

**Comment by bosd** [comment]
Is there an free API available as in free beer? As such micro organisations have access to this?

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by hbrunn** [comment]
@astirpe could you rebase please?

**Pull request closed without merging**
