### PR TITLE
[12.0][MIG] l10n nl dutch company type

### PR DESCRIPTION
**Pull request by NL66278**

### CODE REVIEW

**Review by thomaspaulb — APPROVED** [review]
LGTM, code review. In general try to keep the black/isort/prettier commit separate from the functional commit.

**Review by lfreeke — APPROVED** [review]
Test

**Comment by thomaspaulb** [comment]
@NL66278 Tests are failing on the KVK API keys not being correct.

Should those be updated, or should the KVK API module tests just be using a mocked version of the KVK API? (Latter sounds more logical to me)

**Pull request merged**
