### PR TITLE
[16.0][MIG] l10n_nl_tax_statement

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by NL66278** [comment]
@astirpe Please squash the consecutive translation commits.

**Review by CasVissers-360ERP — APPROVED** [review]
Migration review

**Review by NL66278 — APPROVED** [review]
:+1:  LGTM

**Comment by astirpe** [comment]
Included https://github.com/OCA/l10n-netherlands/pull/394

**Pull request merged**
