### PR TITLE
[15.0][MIG] l10n_nl_tax_statement_icp

### PR DESCRIPTION
**Pull request by astirpe**
Depends on https://github.com/OCA/l10n-netherlands/pull/355

### CODE REVIEW

**Comment by NL66278** [comment]
@astirpe Can you rebase this one and solve any remaining problems?

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Review by thomaspaulb — APPROVED** [review]

**Comment by gjotten** [comment]
@thomaspaulb @NL66278 can either of you retry merging this?

**Pull request merged**
