### PR TITLE
[12.0][FIX] l10n_nl_xaf_auditfile_export: message_post() arguments

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/l10n-netherlands/issues/228.

### CODE REVIEW

**Review by Cravit-Resham — APPROVED** [review]
Issue is resolved.

**Review by CasVissers-360ERP — APPROVED** [review]
Tested, works. Should be merged asap.

**Comment by astirpe** [comment]
The travis failure is unrelated to this PR.
PR https://github.com/OCA/l10n-netherlands/pull/221 should be fixing the travis failure.

**Comment by astirpe** [comment]
Rebased. The merge should now work fine.

**Pull request merged**
