### PR TITLE
[13.0][MIG] l10n_nl_openkvk

### PR DESCRIPTION
**Pull request by astirpe**
Depends on:

- [x] https://github.com/OCA/l10n-netherlands/pull/274
- [x] https://github.com/OCA/l10n-netherlands/pull/275
- [ ] https://github.com/OCA/l10n-netherlands/pull/276

### CODE REVIEW

**Comment by bosd** [comment]
Can this one be reopened and merged?

**Comment by bosd** [comment]
Can you rebase / force push??
To create a runboat.

Is onestein working on migrating this one to v14?

**Comment by bosd** [comment]
Oops, forget my comment for now. I see that the dependency `partner_coc` still is not migrated to V13 and V14

**Review by bosd — CHANGES_REQUESTED** [review]
Results of functional test:
Lookup when entering a COC number goes perfectly.
Adress, business name gets filled.
But the VAT / BTW number does'nt get populated.
(neither other fileds like website and so on.)

Starting a search from a btw nummer in the name field results in an error:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 625, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 311, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 670, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 351, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 340, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1346, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 390, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 377, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/l10n_nl_kvk/models/res_partner.py", line 49, in load_partner_values_from_name
    {"partner_id": self.id, "name": self.name}
  File "<decorator-gen-113>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 317, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/auto/addons/l10n_nl_kvk/wizards/l10n_nl_kvk_preview_wizard.py", line 107, in create
    vals["line_ids"] = self._fetch_kvk_partner_data(vals)
  File "/opt/odoo/auto/addons/l10n_nl_kvk/wizards/l10n_nl_kvk_preview_wizard.py", line 103, in _fetch_kvk_partner_data
    return self._get_wizard_lines(res_data)
  File "/opt/odoo/auto/addons/l10n_nl_openkvk/wizards/l10n_nl_kvk_preview_wizard.py", line 58, in _get_wizard_lines
    return self._get_wizard_lines_openkvk(res_data)
  File "/opt/odoo/auto/addons/l10n_nl_openkvk/wizards/l10n_nl_kvk_preview_wizard.py", line 39, in _get_wizard_lines_openkvk
    all_kvk = res_data.get("dossiernummer", [])
AttributeError: 'list' object has no attribute 'get'
```

**Comment by bosd** [comment]
:pray: @astirpe Can you move forward with this one??

Once this is merged, want to move it forward to V14.

**Comment by astirpe** [comment]
@bosd I would like to do that but it's difficult for me to find enough time in this moment.
This module depends on an old PR https://github.com/OCA/l10n-netherlands/pull/276 that was closed in the meantime and in any case it should be re-adapted with the new API changes: see https://github.com/OCA/l10n-netherlands/pull/345
Do you mind to take over this PR and the other one?

**Comment by bosd** [comment]
Will see what I can do.
( Hope my coding skills are sufficient.) At first I had a little problem understanding the structure of the code.
From an user perspective one would either use the "openkvk" api (for SME's) or official (paid) kvk api.
It is undocumented, the openkvk provides an limited amount of free (as in free beer) lookups.

Having these 2 modules depend on each other from that point of view does not make sense.
But for code re-usage maybe it is.

**Pull request closed without merging**
