### PR TITLE
[11.0][ADD] l10n_nl_location_nuts

### PR DESCRIPTION
**Pull request by astirpe**
Based on the job already made in other OCA localization repositories, this module adapts the Dutch provinces (eventually already loaded in Odoo) with the NUTS locations (see module [base_location_nuts](https://github.com/OCA/partner-contact/tree/11.0/base_location_nuts)).

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]
(I simply believe you looked up the correct codes)

**Review by yung-wang — COMMENTED** [review]
Looking good

**Review by yung-wang — APPROVED** [review]
Looking good

**Review by tarteo — APPROVED** [review]

**Comment by astirpe** [comment]
I think this one can be merged

**Pull request merged**
