### PR TITLE
[13.0][FIX] l10n_nl_location_nuts: test

### PR DESCRIPTION
**Pull request by bosd**
Revert of #382 and now adding the fix in the proper way.
As to @pedrobaeza suggestion.

### CODE REVIEW

**Comment by bosd** [comment]
@thomaspaulb  @NL66278 It's ready

**Review by pedrobaeza — APPROVED** [review]

**Comment by NL66278** [comment]
@pedrobaeza Do you have any idea why runboat is failing on this?

**Comment by pedrobaeza** [comment]
It seems it has started to fail on 13.0. Other example: https://github.com/OCA/account-invoicing/pull/1391

**Review by astirpe — APPROVED** [review]

**Pull request merged**
