### PR TITLE
[FIX][16.0] l10n_nl_xaf_auditfile_export: fix ampersand issue (#397)

### PR DESCRIPTION
**Pull request by thomaspaulb**
This includes:

- Explicit tests for `auditfile_success` after the changes done in #399
- For #397, a better fix than https://github.com/OCA/l10n-netherlands/pull/398
- Tests added for the latter

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]

**Comment by hbrunn** [comment]
@thomaspaulb please rebase

**Comment by thomaspaulb** [comment]
@hbrunn Rebased

@NL66278 A review?

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
