### PR TITLE
[11.0][IMP] l10n_nl_tax_statement: display detailed move lines

### PR DESCRIPTION
**Pull request by astirpe**
With this PR:

- [x] Added buttons in statement lines to view the related move lines in details
- [x] Added tests

### CODE REVIEW

**Review by yung-wang — COMMENTED** [review]
Looks nice, can you also add the drill down to 5b?

**Review by yung-wang — APPROVED** [review]
Works fine here

**Comment by hbrunn** [comment]
@astirpe do you want to squash commits?

**Review by hbrunn — APPROVED** [review]

**Comment by astirpe** [comment]
Squashed. Thanks!

**Pull request merged**
