### PR TITLE
[MIG][15.0] l10n_nl_tax_statement

### PR DESCRIPTION
**Pull request by tarteo**
@espo-tony

### CODE REVIEW

**Comment by astirpe** [comment]
Tests are failing

**Comment by tarteo** [comment]
> Tests are failing

I know. Working on it

**Review by espo-tony — APPROVED** [review]

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
Can this one be merged?

**Review by CasVissers-360ERP — APPROVED** [review]
We have this running for a while now, all seems good!

**Comment by tarteo** [comment]
Can this be merged, please :smile:

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
