### PR TITLE
[11.0][FIX] l10n_nl_tax_statement: add past invoices in report

### LINKED ISSUE #219: [V11] l10n_nl_tax_statement: Update of past undeclared invoices - Update of BTW statement doesn't work
Hello,

i have just checked the V11 version of l10n_nl_tax_statement in order to adopt it for the german "clone" of this module: https://github.com/openbig/l10n-germany/tree/10.0/l10n_de_tax_statement.

I have created a customer invoice with the tax "Verkopen/omzet hoog" with a invoice date in between of the given date_range in the tax statement. If i click on update button the value in the line "1a Leveringen/diensten belast met hoog tarief"  was calculated correctly.

Now i created two further invoices with a invoice date before the "from_date" of the statement. If i go to the tab "Past undeclared invoices" i can see the two lines. Now i wanted to include those lines in the statement by clicking on the ">" arrow to add them + clicking on the "update" button as suggested by the description "Add/Remove the Undeclared Invoices listed below. Afterwards press the Update button in order to recompute the statement lines!".

bildschirmfoto 2019-02-08 um 10 20 50

Now i would normally expect that the line "1a Leveringen/diensten belast met hoog tarief" would have been updated but it doesn't.

bildschirmfoto 2019-02-08 um 10 22 05

Unfortunately it just shows the "regular" invoice in between of the given date range. I miss here the two further added invoices from the past months.

bildschirmfoto 2019-02-08 um 10 22 35

Nevertheless, thanks a lot for your great work on that module. The added feature "past undeclared invoices" is a great further improvement. I will now try to adopt the V11 changes for the german accounting plans.

Best regards
Thorsten

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/l10n-netherlands/issues/219

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by NL66278** [comment]
Most tests succeed, but when excluding the postcode api module, the test fails on a kvk authorization problem.  Travis truly keeps surprising me...

**Comment by NL66278** [comment]
Needs merge of this and then rebase: https://github.com/OCA/l10n-netherlands/pull/392

**Comment by NL66278** [comment]
@astirpe I intend to close all the 11.0 PR's, as it would be quite a lot of work to get them to pass all tests, because of all the problems. Do you agree? The alternative would be to merge them by using the github button, instead of through the OCA bot. Which would be fine by me as well.

**Comment by astirpe** [comment]
@NL66278 no preference by my side, both are fine for me :+1: thanks!

**Pull request merged**
