### PR TITLE
[14.0][FIX] Only include move lines that have been posted in the SQL queries

### PR DESCRIPTION
**Pull request by jeroen-vet**
The SQL queries to get opening balance totals, opening balance entries, move line count and move line total debit and credit did not filter for only posted lines. This fix corrects that.

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@gjotten Are there any cons to not including the unposted lines in the export?

**Comment by gjotten** [comment]
@thomaspaulb it's a workflow thing. We for example have got some moves in a perpetual draft state until year's closing: VAT settlement, profit for the fiscal year, those sorts of things. 

If we were to use an external suite to do monthly/quarterly reports (eg. Visionplanner), then it might be nice to not have to post/unpost those moves on each import. On the other hand, places where I'd expect monthly reporting like that should probably be updating their lock dates and doing at least monthly posting of VAT results.

It might be a wash conceptually, but an accountant will always tell you to only include 'final' moves, and from a business pov the ones doing .xaf exports should be organised enough to handle it.

**Review by thomaspaulb — APPROVED** [review]
Code review only.

@gjotten if you agree functionally then you can leave your positive review also.

**Comment by gjotten** [comment]
> Code review only.
> 
> @gjotten if you agree functionally then you can leave your positive review also.

@thomaspaulb to be honest I'd rather test this functionally on a known db, which I don't have for 14.0, and with ways and means to read out the .xaf easily and not be dependent on CTRL+F in xed. The runbot instance as it is right now doesn't even include demodata for account.moves :-(

@NL66278 and @lfreeke maybe you guys can add this branch on your 14.0 migration?

**Review by CasVissers-360ERP — APPROVED** [review]
I think required from a functional perspective since some/most external reporting tools expect posted moves.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by thomaspaulb** [comment]
Anyone seen this [weird error](https://github.com/OCA/l10n-netherlands/runs/5750195817?check_suite_focus=true) before in another repo and how to solve it?

```
  File "/home/runner/.cache/pre-commit/repo2nxuj_lm/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repo2nxuj_lm/py_env-python3/lib/python3.9/site-packages/click/__init__.py)
```

Perhaps to pin the version of `black` ?

**Comment by thomaspaulb** [comment]
Ah, looks to be [this](https://github.com/psf/black/issues/2964):

```
Please use Black 22.3.0 which was just released to fix this issue or pin Click to 8.0.0, 8.0.1, 8.0.2, 8.0.3, or 8.0.4.
```

**Pull request merged**
