### PR TITLE
[MIG][15.0] l10n_nl_bank

### PR DESCRIPTION
**Pull request by tarteo**
@espo-tony

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by NL66278** [comment]
Question to the author of this module: i suppose some kind of script was used to generate the bank data file from the source data. It might be useful to include that script (if that indeed was used) as well to e able to refresh data in the future (or for future maintenance of this module).

**Comment by tarteo** [comment]
If this is the case then it sounds like good idea :+1: Thanks for reviewing

**Review by astirpe — APPROVED** [review]
As far as I know, the author of this module is not active in OCA anymore

**Review by espo-tony — APPROVED** [review]

**Comment by bosd** [comment]
If such script exsists i am very interested. In the last update I did it manually.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
