### PR TITLE
[12.0][IMP] Tax Statement: multicompany fiscal unit

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/l10n-netherlands/issues/237

Depends on:

- [x] https://github.com/OCA/l10n-netherlands/pull/221

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Does this still allow people to file their NL VAT declarations for each company individually?

**Comment by astirpe** [comment]
In case a group of companies are configured as belonging to a fiscal unit, I assumed that it's possible to declare only one single global tax statement for the whole group. It means that the generation of the single NL VAT declarations for each company of the group is disabled. To create an individual VAT declaration for a single company, this company should be configured as not being part of the fiscal unit. This is what the module does.

**Comment by StefanRijnhart** [comment]
Ah yes, I missed that part where the user has to select the child companies explicitely. Great feature!

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Please review @yung-wang as this was your feature request.

**Comment by yung-wang** [comment]
tested and it works fine.

1. Create 3 companies. Link comp 1 and comp 2 to headoffice.
2. Create invoices in comp 1 and comp 2.

result
I get 1 total tax statement for all the companies.
In the individual companies, i get a separate ICP.

**Comment by astirpe** [comment]
@yung-wang "Files changed" > "Review changes" > "Approve" ?

**Review by yung-wang — APPROVED** [review]
see previous comment

**Pull request merged**
