### PR TITLE
[11.0][FIX] l10n_nl_xaf_auditfile_export: SQL

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]
no worries, I have merged this, so we're both to blame...

**Comment by melroy89** [comment]
Agh no problems, it's fixed fast. Love it

**Review by melroy89 — APPROVED** [review]

**Comment by melroy89** [comment]
You can merge it this time _safely_. I tested it myself also now fully.

Audit xaf (xml) file is created, without errors.

[Auditfile Melden BV 2018.zip](https://github.com/OCA/l10n-netherlands/files/1639904/Auditfile.Melden.BV.2018.zip)

**Comment by melroy89** [comment]
**PATCH HIT!** haha no joking.. have a nice day.

**Comment by astirpe** [comment]
Thank you @danger89 . I hope the .zip file you attached does not contain sensitive data :)

**Comment by melroy89** [comment]
@astirpe I think not, was only demo data from the test database.. No problems.

**Comment by astirpe** [comment]
@danger89 are you sure? I just read your IBAN....
joking ;)
Have you all a nice evening!

**Pull request merged**
