### PR TITLE
[13.0][MIG] l10n_nl_location_nuts

### PR DESCRIPTION
**Pull request by astirpe**
Depends on:

- [x] https://github.com/OCA/partner-contact/pull/800

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
Functional test :+1:

**Comment by NL66278** [comment]
Travis is failing in ocabot on flake8. No reason is logged... Maybe drop flake8, as black should be enough? And I hate it when tools fail without giving any indication why.

**Comment by astirpe** [comment]
I think the flake8 error is this:

```
flake8 except __init__.py................................................Failed
- hook id: flake8
- duration: 0.54s
- exit code: 1

l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py:22:12: E741 ambiguous variable name 'l'
```

It can be fixed by just renaming the variable.

**Review by hbrunn — APPROVED** [review]

**Pull request merged**
