### PR TITLE
[11.0] [MIG] letsencrypt_transip_nl

### PR DESCRIPTION
**Pull request by janverb**
Migration of #259 for OCA/server-tools#1840.

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by NL66278** [comment]
Merge failed because travis ran 5 jobs, seemingly all with the same configuration, and one of the five failed.... Why is it doing this?

**Comment by NL66278** [comment]
Tests op l10n_nl_postcode_api falen nog.

**Comment by janverb** [comment]
It seems that the `l10n_nl_postcode_api` tests are still flaky, even after a rebase (which did touch the module's tests).

Travis passed for 1497f77 but not for 2e9eff8 so I'm sure it's unrelated to what's happening here.

**Comment by janverb** [comment]
I haven't managed to reproduce the test failure locally yet but I found a change that could conceivably fix it, so let's see.

**Comment by janverb** [comment]
@NL66278 Can you try another merge?

**Comment by NL66278** [comment]
@janverb Can you drop the last commit with changes to the postcodeapi? I solved the problems in the postcodeapi here: https://github.com/OCA/l10n-netherlands/pull/330, but that conflicts with these changes.

Maybe you can review my PR?

**Comment by NL66278** [comment]
Replace with this PR to prevent conflicting changes: https://github.com/OCA/l10n-netherlands/pull/340

**Pull request closed without merging**
