### PR TITLE
[14.0][FIX] l10n_nl_tax_statement: don't break when writing list of ids on x2many

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by Stephanvandenberg** [comment]
Tested on a test instance and this PR works

**Review by Stephanvandenberg — APPROVED** [review]
Tested on a test instance and the proposed changes work.

**Review by Stephanvandenberg — APPROVED** [review]

**Review by thomaspaulb — APPROVED** [review]

**Comment by bosd** [comment]
@gjotten Can you please merge?

**Comment by gjotten** [comment]
@NL66278 please merge

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
