### PR TITLE
[FIX] Limit userID to maximum 35 characters

### LINKED ISSUE #71: [9.0] XAF audit file export fails with long login (E-Mail)
With the new 9.0 module, the export fails when the user doing the entries logs in with an emailadres.
The error message:

<pre>
:5228:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}userID': [facet 'maxLength'] The value has a length of '37'; this exceeds the allowed maximum length of '35'.
:5228:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}userID': 'p.pietjepuk@pietjepukenterprisesbv.nl' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}IdentificationString35'.
</pre>

We are using google authentication, therefore we can't change the login.
Proposed solutions:
- Replace the login with the part before the @, if the login contains an @.
- Truncate the login to 35 characters.. This usually truncates the last part of the domain,
- Use the name, of another field?

If someone can give feedback, I can create a patch for this.

### PR DESCRIPTION
**Pull request by RoelAdriaans**
Fixes #71

### CODE REVIEW

**Comment by pankk** [comment]
Looks like this would work in practice, but in theory, is a unique userID required?
For example, if we have the following logins:
'pietjepukenterprisesholdingcompany01@something.com'
'pietjepukenterprisesholdingcompany02@something.com'
'pietjepukenterprisesholdingcompany03@something.com'
We'd truncate them all to just 'pietjepukenterprisesholdingcompany0'. Would this be a problem?

**Review by hbrunn — CHANGES_REQUESTED** [review]
If you want to shorten fields, use a widget as the other fields do, you'll have to declare a new one in https://github.com/OCA/l10n-netherlands/blob/9.0/l10n_nl_xaf_auditfile_export/models/ir_qweb.py

But given we only need an ID here, why not use the user's ID here anyways? This would also address @pankk's concern

**Comment by RoelAdriaans** [comment]
@hbrunn I tried making a widget, but it didn't work. See my commit: https://github.com/RoelAdriaans-B-informed/l10n-netherlands/commit/c5160e8dc1fa97170aa10e259a1c17804ea92ea8 , still fails.
But, I think that's an issue with the widget, debugging shows that _format() is never called... 

Indeed, @pankk has a valid point with the usernames, that's why I asked for feedback in #71 . No problems with using an ID here, standard makes this possible ( http://www.ictplaza.nl/uploads/xml_auditfiles/xmlfinancieel/20140402_AuditfileFinancieelVersie_3_2.zip , file XmlAuditfileFinancieel3.2_FunHie.rtf ). It also defines a basics table linking the userid to the real username..

**Comment by hbrunn** [comment]
the widgets not being used will be a problem anyways, this worked in 8.0 - that seems an oversight during the migration to 9.0. This will cause a lot of other issues too for too long character fields, so it's certainly something to look into

**Comment by astirpe** [comment]
@RoelAdriaans-B-informed with commit https://github.com/astirpe/l10n-netherlands/commit/5f7d133ff739e3c4387834c546f8fca8550e5cde the widgets should work. Could you check?
I opened the pull request https://github.com/RoelAdriaans-B-informed/l10n-netherlands/pull/1 to your branch.

**Comment by hbrunn** [comment]
fixed in d9931e2, closing this

**Comment by astirpe** [comment]
@hbrunn I think this one is not fixed yet. Am I missing something?

**Comment by hbrunn** [comment]
@astirpe yes, your own backport of the proper fix: https://github.com/OCA/l10n-netherlands/pull/94 ;-)

**Comment by astirpe** [comment]
@hbrunn I see, but this PR says: "[FIX] Limit userID to maximum 35 characters".
And the userID length was not touched in the main repository.

Moreover, in this PR there is a discussion still pending, regarding the adoption of the ID of the user instead of the truncation of the user.login, as it was initially proposed.

**Comment by hbrunn** [comment]
right, a bit premature, thanks. Then it just needs fixing

**Comment by astirpe** [comment]
Thanks!

... and by the way I vote for the adoption of the user ID, instead of the actual user login.

**Review by astirpe — CHANGES_REQUESTED** [review]
@RoelAdriaans-B-informed if you agree, you could replace `write_uid.login` with `write_uid.id`. If you also bump the version number, this PR is ready to be merged IMO.

**Comment by RoelAdriaans** [comment]
I agree with the user id. Committed and bumped version

**Review by astirpe — APPROVED** [review]

**Pull request merged**
