### PR TITLE
fix CBS export Bus #112

### PR DESCRIPTION
**Pull request by ploegvde**
Fix for #112

### CODE REVIEW

**Comment by hbrunn** [comment]
fix CI please

**Comment by bizzappdev** [comment]
CLA for the Jimeet Darji is missing to solve that today morning I have signed ECLA from BizzAppDev for @bizzappdev account. Please verify it and let us know in case we need to do any further things.

**Comment by ploegvde** [comment]
Is this ok now for merge?

**Comment by hbrunn** [comment]
CI still fails

**Comment by bizzappdev** [comment]
CI failed because of the code coverage, this module has already  92.24% 
the newly added condition is for either invoice line total is 0 or in one invoice has more than 99 invoice line.
do you really want me to have the test case for those conditions?

**Comment by hbrunn** [comment]
if you want to discuss rules, do so on https://github.com/OCA/maintainer-quality-tools. For the time being, I'll execute the rules, and they say: Green CI

**Comment by ploegvde** [comment]
@hbrunn Is a functional test also ok? testcase for this seems to much. If you want i can test it.

**Comment by astirpe** [comment]
@ploegvde I'm noticing that you removed the repository containing the code of this PR. It seems to me that you're not going to continue to work on this PR. Is it the case?

**Comment by ploegvde** [comment]
No sorry Andrea, We will not work for OCA anymore.

**Comment by StefanRijnhart** [comment]
That's sad to hear @ploegvde

**Pull request closed without merging**
