### PR TITLE
[16.0][MIG] l10n_nl_account_tax_unece

### PR DESCRIPTION
**Pull request by astirpe**
Depends on https://github.com/OCA/community-data-files/pull/172

### CODE REVIEW

**Review by bosd — APPROVED** [review]
LGTM 👍

**Comment by astirpe** [comment]
Rebased. Also changed license from AGPL to LGPL, so this PR now depends on https://github.com/OCA/community-data-files/pull/172

**Comment by thomaspaulb** [comment]
Hm, the test fails with

```
2023-10-31 11:15:43,571 268 ERROR odoo odoo.addons.l10n_nl_account_tax_unece.tests.test_nl_account_tax_unece: FAIL: TestNlAccountTaxUnece.test_existing_coa_update
Traceback (most recent call last):
  File "/__w/l10n-netherlands/l10n-netherlands/l10n_nl_account_tax_unece/tests/test_nl_account_tax_unece.py", line 63, in test_existing_coa_update
    self.assertTrue(tax.unece_type_id.id == unece_type_id)
AssertionError: False is not true
```

**Comment by astirpe** [comment]
Seems the tests are failing after https://github.com/odoo/odoo/commit/b63f21b9bd445e352ff9505ea62eb2193bf2ab1e since a new tax template `"btw_X0_ABC_levering"`  was added in `l10n_nl`.

**Comment by bosd** [comment]
Please have a look at this PR, https://github.com/OCA/l10n-netherlands/pull/404 to update the category's.
Maybe we can incorporate that, before the migration to V16.

**Comment by astirpe** [comment]
@bosd yes indeed it could be fixed all-in-once. I will include your fixes but unfortunately I'm not able to verify myself whether they are correct or not.

**Comment by bosd** [comment]
Sorry, I forgot about that PR. Continued working on it..
Now ready for 14 and 15 branch.
When you include it here, it might fix the tests :thinking:

**Comment by NL66278** [comment]
@astirpe So these are the two test failures, bot related to COA:
```
2023-10-31T11:15:43.5728662Z 2023-10-31 11:15:43,571 268 [1;31m[1;49mERROR[0m odoo odoo.addons.l10n_nl_account_tax_unece.tests.test_nl_account_tax_unece: FAIL: TestNlAccountTaxUnece.test_existing_coa_update
2023-10-31T11:15:43.5730016Z Traceback (most recent call last):
2023-10-31T11:15:43.5731325Z   File "/__w/l10n-netherlands/l10n-netherlands/l10n_nl_account_tax_unece/tests/test_nl_account_tax_unece.py", line 63, in test_existing_coa_update
2023-10-31T11:15:43.5732615Z     self.assertTrue(tax.unece_type_id.id == unece_type_id)
2023-10-31T11:15:43.5733237Z AssertionError: False is not true
2023-10-31T11:15:43.5733662Z 

---

2023-10-31T11:15:47.0571298Z 2023-10-31 11:15:47,051 268 [1;31m[1;49mERROR[0m odoo odoo.addons.l10n_nl_account_tax_unece.tests.test_nl_account_tax_unece: FAIL: TestNlAccountTaxUnece.test_load_coa
2023-10-31T11:15:47.0572735Z Traceback (most recent call last):
2023-10-31T11:15:47.0574052Z   File "/__w/l10n-netherlands/l10n-netherlands/l10n_nl_account_tax_unece/tests/test_nl_account_tax_unece.py", line 41, in test_load_coa
2023-10-31T11:15:47.0575279Z     self.assertTrue(tax.unece_type_id.id == unece_type_id)
2023-10-31T11:15:47.0575898Z AssertionError: False is not true
2023-10-31T11:15:47.0576306Z  

```
Instead of assertTrue and then an equal comparison, maybe better do an assertEqual. Then on failure you will have both values in the log, making it easier to get to the root of the problem.

**Comment by hbrunn** [comment]
superseded by https://github.com/OCA/l10n-netherlands/pull/417

**Pull request closed without merging**
