### PR TITLE
[12.0][MIG] l10n nl country states

### PR DESCRIPTION
**Pull request by NL66278**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@NL66278 Could you try rebasing?

**Comment by NL66278** [comment]
@thomaspaulb Rebase done and corrected. Please leave review.

**Review by thomaspaulb — APPROVED** [review]
Looks good just squash the last two commits with the migration commit

**Review by lfreeke — APPROVED** [review]
Test

**Comment by NL66278** [comment]
@astirpe Hi Andrea, refraining from merging my own PR's, could you merge this one (and maybe others that are ready to merge).

**Comment by astirpe** [comment]
I think I don't have enough permits for merging in this repo. Let's see:

/ocabot rebase

**Comment by NL66278** [comment]
@astirpe why a rebase instead of a merge?

**Comment by astirpe** [comment]
Just to try if I had permits

**Pull request merged**
