### PR TITLE
[ADD] l10n_nl_postcodeapi

### PR DESCRIPTION
**Pull request by hbrunn**
@StefanRijnhart's code that seems to never have made it in 7.

### CODE REVIEW

**Comment by NL66278** [comment]
Maybe needed to update travis configuration to include partner-contact repository?

oca dependencies is missing in 7.0 branch.

**Comment by hbrunn** [comment]
runbot error is expected as it doesn't support dependencies yet

**Comment by NL66278** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by hbrunn** [comment]
@NL66278 @StefanRijnhart thanks! Now that version 0.2 is published on pypi, we nearly support the new api with this modules. Version 0.2 still defaults to v1 of the postcode api, should we pass version 2 as parameter in this modules or release a version 0.2.1 of the library which defaults to v2?

**Pull request merged**
