### PR TITLE
7.0 l10n nl postcodeapi

### PR DESCRIPTION
**Pull request by NL66278**
DO NOT MERGE YET. Checking oca_dependencies.txt

### CODE REVIEW

**Comment by NL66278** [comment]
Strange: not one error to be seen , still saying build failed??

**Comment by hbrunn** [comment]
@NL66278 is this a duplicate of #29?

**Comment by NL66278** [comment]
@hbrunn  I think it is. Shall I close this one?

**Comment by hbrunn** [comment]
yes, please. And you might thumb up the other one ;-)

**Comment by NL66278** [comment]
Duplicate with Holgers PR.

**Pull request closed without merging**
