### PR TITLE
[14.0] l10n_nl_xaf_auditfile_export: include lines from inactive journals

### PR DESCRIPTION
**Pull request by antonioburic**
v14 port of #343 

edit: precommit/black seems to fail for a reason unknown to me, doesn't seem related

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM

**Review by astirpe — APPROVED** [review]

**Comment by NL66278** [comment]
@antonioburic Please rebase on current 14.0, that should solve the pre-commit problem

**Comment by antonioburic** [comment]
Thanks @NL66278 done ^^

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
