### PR TITLE
[ADD] transifex support

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by astirpe** [comment]
@hbrunn Thank you! To test it is it necessary that PR is merged first? If this is the case, then could we say: fast track + optimistic merge?

**Comment by hbrunn** [comment]
my understanding is that we can verify this on https://www.transifex.com/oca/public as soon as travis has done its thing, so let's wait for it to pick this up

**Comment by pedrobaeza** [comment]
You can merge as soon as the TRANSIFEX Travis stage is green

**Comment by hbrunn** [comment]
yes, we'll have to merge this: https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_run_tests#L63

**Comment by hbrunn** [comment]
thanks @pedrobaeza, I concluded the same

**Comment by hbrunn** [comment]
seems to have worked. I took the liberty to push similar commits to 8.0 and 9.0 directly

**Comment by ploegvde** [comment]
Thanks a lot! I have translated all modules V8, V9 and V10. Ping me if new modules arrive and need translation. I will do it.

**Pull request merged**
