### PR TITLE
[UPD] Current list of ISO codes from Wikipedia

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
Version in manifest should be increased

**Comment by StefanRijnhart** [comment]
I consider version bumps harmful. I now run this code in production with another unmerged PR on this project. At build time, I merge both PRs. If I bump the version in this PR, my build fails. See https://github.com/OCA/maintainer-tools/issues/314

**Comment by pedrobaeza** [comment]
Yes, but meanwhile we should do it manually. You can do it if you prefer when merging.

**Comment by StefanRijnhart** [comment]
Merge time is good for me

**Comment by hbrunn** [comment]
is there a convenient way to do this as merge time?

**Review by hbrunn — CHANGES_REQUESTED** [review]
/

**Review by hbrunn — APPROVED** [review]

**Review by CasVissers-360ERP — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
@pedrobaeza how to modify the module version number at merge time?

**Comment by pedrobaeza** [comment]
I mean adding a commit after merging. We are handling the git bot however.

**Comment by hbrunn** [comment]
as a maintainer I don't really like the idea of doing this myself. @StefanRijnhart if you add that in the common hours and ping me, I'll merge immediately

**Comment by StefanRijnhart** [comment]
Done

**Comment by hbrunn** [comment]
ci error unrelated

**Pull request merged**
